<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>myCurrency</title>

        <!-- Fonts -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <!-- Styles -->
        
    </head>
    <body>
    <table class="pure-table">
        <thead>
            <tr>
                <th>Currency 1</th>
                <th>Currency 2</th>
                <th>Rate</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>USD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>CAD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>HKD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>ISK</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>PHP</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>DKK</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>HUF</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>CZK</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>GBP</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>RON</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>SEK</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>IDR</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>INR</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>BRL</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>RUB</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>HRK</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>JPY</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>THB</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>CHF</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>EUR</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>MYR</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>BGN</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>TRY</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>CNY</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>NOK</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>NZD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>ZAR</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>USD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>MXN</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>SGD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>AUD</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>ILS</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>KRW</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>PLN</td>
                <td></td>
                <td></td>
            </tr>

        </tbody>
    </table>

    <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>
